version: '3'

services:

  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  nginx:
    image: linuxserver/nginx
    ports:
      - "443:443"
    volumes:
      - /docker/nginx:/config
      - ./nginx/default:/defaults/default
      - ./nginx/default.d:/etc/nginx/default.d
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}

  rutorrent:
    image: linuxserver/rutorrent
    ports:
      - "51413:51413"
      - "6881:6881/udp"
    expose:
      - "80"
      - "5000"
    volumes:
      - /docker/rutorrent:/config
      - ${DOWNLOAD_DIR}:/downloads
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}


  jackett:
    image: linuxserver/jackett
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${JACKETT_CONFIG}:/config
      - ${BLACKHOLE_DIR}:/downloads
    expose:
      - "9117"
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}

  sonarr:
    image: linuxserver/sonarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SONARR_CONFIG}:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${TV_DIR}:/tv:nocopy
    expose:
      - "8989"
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}

  radarr:
    image: linuxserver/radarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${RADARR_CONFIG}:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${MOVIES_DIR}:/movies:nocopy
    expose:
      - "7878"
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}

