version: '3'

services:

  traefik:
    image: traefik
    command:  --docker.domain=$DOMAIN
    environment:
      DOMAIN: $DOMAIN
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ${TRAEFIK_CONFIG}:/config

  rutorrent:
    image: linuxserver/rutorrent
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:rutorrent.$DOMAIN"
    restart: always
    ports:
      - "51413:51413"
      - "6881:6881/udp"
    expose:
      - "80"
      - "5000"
    volumes:
      - ${RUTORRENT_CONFIG}:/config
      - ${DOWNLOAD_DIR}:/downloads
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}


  jackett:
    image: linuxserver/jackett
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:jackett.$DOMAIN"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${JACKETT_CONFIG}:/config
      - ${BLACKHOLE_DIR}:/downloads
    expose:
      - "9117"
    environment:
      JACKETT_KEY: ${JACKETT_KEY}
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}

  sonarr:
    image: linuxserver/sonarr
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:sonarr.$DOMAIN"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SONARR_CONFIG}:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${TV_DIR}:/tv:nocopy
    expose:
      - "8989"
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}

  radarr:
    image: linuxserver/radarr
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:radarr.$DOMAIN"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${RADARR_CONFIG}:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${MOVIES_DIR}:/movies:nocopy
    expose:
      - "7878"
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}

