version: '3'
services:

  mysql:
    image: mysql

    ports:
      - 3306:3306

    volumes:
      - /docker/mysql:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: mypasswd

  rtorrent:
    build: ./rtorrent
    volumes:
      - ${DOWNLOAD_DIR}:/downloads
    ports:
      - "80:80"
      - "443:443"
      - "49160:49160/udp"
      - "49161:49161"
    expose:
      - "5000"

  sickrage:
    build: ./sickrage
    volumes:
      - ${SICKRAGE_CONFIG}:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${TV_DIR}:/tv
    expose:
      - "8081"
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}

      KODI_HOST: ${KODI_HOST}
      KODI_PORT: ${KODI_PORT}
      KODI_USER: ${KODI_USER}
      KODI_PASSWORD: ${KODI_PASSWORD}

    healthcheck:
      test: ["[", "-f", "/tv/.health", "]"]
      interval: 10s
      timeout: 5s
      retries: 3

  couchpotato:
    build: ./couchpotato
    volumes:
      - ${COUCHPOTATO_CONFIG}:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${MOVIES_DIR}:/movies
    expose:
      - "5050"
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}

      KODI_HOST: ${KODI_HOST}
      KODI_PORT: ${KODI_PORT}
      KODI_USER: ${KODI_USER}
      KODI_PASSWORD: ${KODI_PASSWORD}

    healthcheck:
      test: ["[", "-f", "/movies/.health", "]"]
      interval: 10s
      timeout: 5s
      retries: 3

