version: '2'
services:

  rtorrent:
    build: ./rtorrent
    volumes:
      - ${DOWNLOAD_DIR}:/downloads
    ports:
      - "80:80"
      - "443:443"
      - "49160:49160/udp"
      - "49161:49161"
    expose:
      - "5000"

  sickrage:
    build: ./sickrage
    volumes:
      - ${SICKRAGE_CONFIG}:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${TV_DIR}:/tv
    expose:
      - "8081"
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}

  couchpotato:
    build: ./couchpotato
    volumes:
      - ${COUCHPOTATO_CONFIG}:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${MOVIES_DIR}:/movies
    expose:
      - "5050"
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}

